<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Spatie\Translatable\HasTranslations;

class HomePost extends Model
{
    use HasTranslations;

    protected $fillable = [
        'header_image',
        'home',
        'services',
        'projects',
        'infos',
        'contact',
        'about_us',
        'faqs',
        'banner_title',
        'banner_subtitle',
        'banner_text_item_first',
        'banner_text_item_second',
        'banner_text_item_third',
        'banner_text_item_fourth',
        'banner_description',
        'button_first',
        'button_second',
        'service_title_first',
        'service_title_second',
        'service_title_third',
        'service_title_fourth',
        'service_description',
        'service_item_first',
        'service_item_second',
        'service_item_third',
        'service_item_fourth',
        'service_image_first',
        'service_image_second',
        'service_image_third',
        'service_image_fourth',
        'project_title_first',
        'project_title_second',
        'project_title_third',
        'project_description',
        'project_subtitle_first',
        'project_subtitle_second',
        'project_subtitle_third',
        'project_subtitle_fourth',
        'project_subtitle_fifth',
        'project_subtitle_sixth',
        'project_image_first',
        'project_image_second',
        'project_image_third',
        'project_image_fourth',
        'project_image_fifth',
        'project_image_sixth',
        'info_title_first',
        'info_title_second',
        'info_title_third',
        'info_title_fourth',
        'info_description_first',
        'skill_step_first',
        'skill_step_second',
        'skill_step_third',
        'info_description_second',
        'cta_section_item_first',
        'cta_section_item_second',
        'cta_section_item_third',
        'cta_section_contact_item_first',
        'cta_section_contact_item_second',
        'cta_section_contact_item_third',
        'firstname',
        'lastname',
        'email',
        'subject',
        'message',
        'send_message',
    ];

    public array $translatable = [
        'home',
        'services',
        'projects',
        'infos',
        'contact',
        'about_us',
        'faqs',
        'banner_title',
        'banner_subtitle',
        'banner_text_item_first',
        'banner_text_item_second',
        'banner_text_item_third',
        'banner_text_item_fourth',
        'banner_description',
        'button_first',
        'button_second',
        'service_title_first',
        'service_title_second',
        'service_title_third',
        'service_title_fourth',
        'service_description',
        'service_item_first',
        'service_item_second',
        'service_item_third',
        'service_item_fourth',
        'project_title_first',
        'project_title_second',
        'project_title_third',
        'project_description',
        'project_subtitle_first',
        'project_subtitle_second',
        'project_subtitle_third',
        'project_subtitle_fourth',
        'project_subtitle_fifth',
        'project_subtitle_sixth',
        'info_title_first',
        'info_title_second',
        'info_title_third',
        'info_title_fourth',
        'info_description_first',
        'skill_step_first',
        'skill_step_second',
        'skill_step_third',
        'info_description_second',
        'cta_section_item_first',
        'cta_section_item_second',
        'cta_section_item_third',
        'cta_section_contact_item_first',
        'cta_section_contact_item_second',
        'cta_section_contact_item_third',
        'firstname',
        'lastname',
        'email',
        'subject',
        'message',
        'send_message',
    ];

    protected $casts = [
        'home' => 'array',
        'services' => 'array',
        'projects' => 'array',
        'infos' => 'array',
        'contact' => 'array',
        'about_us' => 'array',
        'faqs' => 'array',
        'banner_title' => 'array',
        'banner_subtitle' => 'array',
        'banner_text_item_first' => 'array',
        'banner_text_item_second' => 'array',
        'banner_text_item_third' => 'array',
        'banner_text_item_fourth' => 'array',
        'banner_description' => 'array',
        'button_first' => 'array',
        'button_second' => 'array',
        'service_title_first' => 'array',
        'service_title_second' => 'array',
        'service_title_third' => 'array',
        'service_title_fourth' => 'array',
        'service_description' => 'array',
        'service_item_first' => 'array',
        'service_item_second' => 'array',
        'service_item_third' => 'array',
        'service_item_fourth' => 'array',
        'project_title_first' => 'array',
        'project_title_second' => 'array',
        'project_title_third' => 'array',
        'project_description' => 'array',
        'project_subtitle_first' => 'array',
        'project_subtitle_second' => 'array',
        'project_subtitle_third' => 'array',
        'project_subtitle_fourth' => 'array',
        'project_subtitle_fifth' => 'array',
        'project_subtitle_sixth' => 'array',
        'info_title_first' => 'array',
        'info_title_second' => 'array',
        'info_title_third' => 'array',
        'info_title_fourth' => 'array',
        'info_description_first' => 'array',
        'skill_step_first' => 'array',
        'skill_step_second' => 'array',
        'skill_step_third' => 'array',
        'info_description_second' => 'array',
        'cta_section_item_first' => 'array',
        'cta_section_item_second' => 'array',
        'cta_section_item_third' => 'array',
        'cta_section_contact_item_first' => 'array',
        'cta_section_contact_item_second' => 'array',
        'cta_section_contact_item_third' => 'array',
        'firstname' => 'array',
        'lastname' => 'array',
        'email' => 'array',
        'subject' => 'array',
        'message' => 'array',
        'send_message' => 'array',
    ];
}
