<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Spatie\Translatable\HasTranslations;

class AboutPost extends Model
{

use HasTranslations;

protected $fillable = [
'header_text', 
'header_description',
'header_image',
'section_text',
'menu_first_title',
'menu_second_title',
'menu_third_title',
'menu_fourth_title',
'menu_first_subtitle',
'menu_second_subtitle',
'menu_third_subtitle',
'menu_fourth_subtitle',
'menu_first_description',
'menu_second_description',
'menu_third_description',
'menu_fourth_description',
'menu_first_image',
'menu_second_image',
'menu_third_image',
'menu_fourth_image',
'home',
'about_us',
'faqs',
'contact',
'firstname',
'lastname',
'email',
'message',
'send_message',
'button_first',
'button_second',
'header_text_item_first',
'header_text_item_second',
'section_heading_title_first',
'section_heading_title_second',
'section_heading_description',
'skill_first',
'skill_second',
'skill_third',
'step_first',
'step_second',
'step_third',
'cta_section_item_first',
'cta_section_item_second',
'cta_section_item_third',
'cta_section_item_fourth',
'cta_section_contact_item_first',
'cta_section_contact_item_second',
'cta_section_contact_item_third',
];

public array $translatable = 
[
'header_text', 
'header_description',
'section_text',
'menu_first_title',
'menu_second_title',
'menu_third_title',
'menu_fourth_title',
'menu_first_subtitle',
'menu_second_subtitle',
'menu_third_subtitle',
'menu_fourth_subtitle',
'menu_first_description',
'menu_second_description',
'menu_third_description',
'menu_fourth_description',
'home',
'about_us',
'faqs',
'contact',
'firstname',
'lastname',
'email',
'message',
'send_message',
'button_first',
'button_second',
'header_text_item_first',
'header_text_item_second',
'section_heading_title_first',
'section_heading_title_second',
'section_heading_description',
'skill_first',
'skill_second',
'skill_third',
'step_first',
'step_second',
'step_third',
'cta_section_item_first',
'cta_section_item_second',
'cta_section_item_third',
'cta_section_item_fourth',
'cta_section_contact_item_first',
'cta_section_contact_item_second',
'cta_section_contact_item_third',
];

protected $casts = [
'header_text' => 'array', 
'header_description' => 'array',
'section_text' => 'array',
'menu_first_title' => 'array',
'menu_second_title' => 'array',
'menu_third_title' => 'array',
'menu_fourth_title' => 'array',
'menu_first_subtitle' => 'array',
'menu_second_subtitle' => 'array',
'menu_third_subtitle' => 'array',
'menu_fourth_subtitle' => 'array',
'menu_first_description' => 'array',
'menu_second_description' => 'array',
'menu_third_description' => 'array',
'menu_fourth_description' => 'array',
'home' => 'array',
'about_us' => 'array',
'faqs' => 'array',
'contact' => 'array',
'firstname' => 'array',
'lastname' => 'array',
'email' => 'array',
'message' => 'array',
'send_message' => 'array',
'button_first' => 'array',
'button_second' => 'array',
'header_text_item_first' => 'array',
'header_text_item_second' => 'array',
'section_heading_title_first' => 'array',
'section_heading_title_second' => 'array',
'section_heading_description' => 'array',
'skill_first' => 'array',
'skill_second' => 'array',
'skill_third' => 'array',
'step_first' => 'array',
'step_second' => 'array',
'step_third' => 'array',
'cta_section_item_first' => 'array',
'cta_section_item_second' => 'array',
'cta_section_item_third' => 'array',
'cta_section_item_fourth' => 'array',
'cta_section_contact_item_first' => 'array',
'cta_section_contact_item_second' => 'array',
'cta_section_contact_item_third' => 'array',
];
}

